// TODO: FOR THE LOVE OF GODS, CLEAN THIS UP.

#include <shaderc/shaderc.h>

#include <shaderc/shaderc.hpp>
#include <vector>

#include "base/base.hpp"

struct ShaderInfo {
    std::string           name;
    shaderc_shader_kind   kind;
    std::vector<uint32_t> bytecode;

    ShaderInfo(const std::string& name_, shaderc_shader_kind kind_,
               const std::vector<uint32_t>& bytecode_)
        : name(name_), kind(kind_), bytecode(bytecode_) {}
};

// NOTE: Panics if compilation fails.
std::vector<nbody::U32> compile_glsl(const std::string& name, shaderc_shader_kind kind,
                                     const std::string& source) {
    shaderc::Compiler       compiler;
    shaderc::CompileOptions options;
    options.SetTargetEnvironment(shaderc_target_env_vulkan, shaderc_env_version_vulkan_1_1);
    options.SetOptimizationLevel(shaderc_optimization_level_performance);

    shaderc::SpvCompilationResult result =
        compiler.CompileGlslToSpv(source, kind, name.c_str(), options);

    ASSERT(result.GetCompilationStatus() == shaderc_compilation_status_success,
           "Compilation failed");

    return {result.begin(), result.end()};
}

std::string generate_source_code(const ShaderInfo& info) {
    std::string s{};

    s += "// This file has been generated by gfx_shader_embed\n\n";
    s += "#pragma once\n\n";
    s += "#include <vector>\n\n";
    s += "#include \"base/base.hpp\"\n\n";
    s += "namespace nbody {\n";
    s += "namespace embeds {\n";

    s += "static std::vector<U32> " + info.name + " = {";

    for (auto it = info.bytecode.begin(); it != info.bytecode.end(); ++it) {
        s += std::to_string(*it);
        if (std::next(it) != info.bytecode.end()) {
            s += ", ";
        }
    }

    s += "};";
    s += "\n}\n";
    s += "}\n";

    return s;
}

int main() {
    nbody::Logger::init();

    std::vector<std::string> shader_filepaths =
        nbody::dir_list_file_names("shaders").value_or(std::vector<std::string>());

    std::vector<ShaderInfo> shader_infos{};

    for (const std::string& filepath : shader_filepaths) {
        auto [name, kind_string] = nbody::filename_split_by_extension(filepath);
        std::string source       = nbody::file_read_as_string("shaders/" + filepath).value_or("");

        ASSERT(!source.empty(), "Shader source is empty");

        if (kind_string == "vert") {
            shader_infos.push_back(ShaderInfo(name + "_vert", shaderc_vertex_shader,
                                              compile_glsl(name, shaderc_vertex_shader, source)));
        } else if (kind_string == "frag") {
            shader_infos.push_back(ShaderInfo(name + "_frag", shaderc_fragment_shader,
                                              compile_glsl(name, shaderc_fragment_shader, source)));
        }
    }

    ASSERT(!shader_infos.empty(), "No shaders found");

    for (const ShaderInfo& info : shader_infos) {
        std::string s = generate_source_code(info);
        nbody::file_write("src/embeds/" + info.name + ".hpp", s);
    }

    return 0;
}
