#include <shaderc/shaderc.h>

#include <algorithm>
#include <cctype>
#include <shaderc/shaderc.hpp>

#include "base/assert.hpp"
#include "base/fs.hpp"
#include "base/log.hpp"
#include "base/type.hpp"

struct ShaderCompileInfo {
    std::string         name;
    shaderc_shader_kind kind;
    std::string         source;
};

struct ShaderBytecodeInfo {
    std::string         name;
    shaderc_shader_kind kind;
    Bytecode            bytecode;
};

struct ShaderInputInfo {
    std::string         name;
    shaderc_shader_kind kind;
    std::string         path;
};

std::optional<ShaderBytecodeInfo> compile(const ShaderCompileInfo& info) {
    ASSERT(!info.name.empty(), "Shader name cannot be empty");
    ASSERT(!info.source.empty(), "Shader source cannot be empty");

    shaderc::Compiler       compiler;
    shaderc::CompileOptions options;

    options.SetTargetEnvironment(shaderc_target_env_vulkan, shaderc_env_version_vulkan_1_1);
    options.SetOptimizationLevel(shaderc_optimization_level_performance);

    shaderc::SpvCompilationResult result =
        compiler.CompileGlslToSpv(info.source, info.kind, info.name.c_str(), options);

    if (result.GetCompilationStatus() != shaderc_compilation_status_success) {
        LOG_APP_ERROR("Compilation failed");
        return std::nullopt;
    }

    return ShaderBytecodeInfo{
        .name = info.name, .kind = info.kind, .bytecode = Bytecode{result.begin(), result.end()}
    };
}

std::string generate_code(const ShaderBytecodeInfo& info) {
    ASSERT(!info.name.empty(), "Shader name cannot be empty");
    ASSERT(!info.bytecode.empty(), "Shader bytecode cannot be empty");

    std::string bytecode_symbol = info.name + "_bytecode";

    std::transform(bytecode_symbol.begin(), bytecode_symbol.end(), bytecode_symbol.begin(),
                   toupper);

    std::string bytecode_string{};

    for (USize i = 0; i < info.bytecode.size(); ++i) {
        bytecode_string += std::to_string(info.bytecode[i]);
        if (i + 1 < info.bytecode.size()) {
            bytecode_string += ", ";
        }
    }

    std::string s{};

    s += "// NOTE: This file has been generated by generate_shader_embeds.\n";
    s += "// WARNING: Do not edit this file manually.\n";
    s += "\n";
    s += "#include \"base/type.hpp\"\n";
    s += "\n";
    s += "namespace embed {\n";
    s += "static const Bytecode " + bytecode_symbol + " = {" + bytecode_string + "};\n";
    s += "} // namespace embed\n";

    return s;
}

int main() {
    LOG_INIT_DEFAULT();

    const std::string output_dir_path = "include/embed/";

    std::vector<ShaderInputInfo> input_infos = {
        {"vk_vert_triangle", shaderc_vertex_shader,   "shaders/triangle.vert"},
        {"vk_frag_triangle", shaderc_fragment_shader, "shaders/triangle.frag"}
    };

    LOG_APP_INFO("Output directory: " + output_dir_path);
    LOG_APP_INFO("Shaders to embed: " + std::to_string(input_infos.size()));

    std::vector<ShaderBytecodeInfo> bytecode_infos{};
    bytecode_infos.reserve(input_infos.size());

    for (const ShaderInputInfo& input_info : input_infos) {
        std::optional<std::string> source_result = base::file_read_as_string(input_info.path);

        ASSERT(source_result.has_value(), "Failed to read shader source -> " + input_info.path);

        LOG_APP_INFO("Compiling shader: " + input_info.name);
        std::optional<ShaderBytecodeInfo> bytecode_result = compile({
            .name   = input_info.name,
            .kind   = input_info.kind,
            .source = source_result.value(),
        });

        ASSERT(bytecode_result.has_value(), "Failed to compile shader");

        bytecode_infos.push_back(bytecode_result.value());
    }

    ASSERT(bytecode_infos.size() == input_infos.size(), "Bytecode count mismatch");

    for (const ShaderBytecodeInfo& bytecode_info : bytecode_infos) {
        std::string output_file_path = output_dir_path + bytecode_info.name + ".hpp";
        std::string code             = generate_code(bytecode_info);

        LOG_APP_INFO("Writing shader: " + bytecode_info.name);
        base::file_write(output_file_path, code);
    }

    return 0;
}
