// NOTE: This file has been generated by generate_shader_embeds.
// WARNING: Do not edit this file manually.

#include "base/type.hpp"

namespace embed {
static const Bytecode VK_FRAG_TRIANGLE_BYTECODE = {
    3,  0,  11, 19, 0,  17, 1,  11, 1,  71,  46, 46, 0,  14, 0,  1,  15, 4,  4,   109, 0,  9,
    12, 16, 4,  7,  71, 9,  30, 0,  71, 12,  30, 0,  19, 2,  33, 3,  2,  22, 6,   32,  23, 7,
    6,  4,  32, 8,  3,  7,  59, 8,  9,  3,   23, 10, 6,  3,  32, 11, 1,  10, 59,  11,  12, 1,
    43, 6,  14, 0,  54, 2,  4,  0,  3,  248, 5,  61, 10, 13, 12, 81, 6,  15, 13,  0,   81, 6,
    16, 13, 1,  81, 6,  17, 13, 2,  80, 7,   18, 15, 16, 17, 14, 62, 9,  18, 253, 56};
}  // namespace embed
